<section>
    <div class="container m-auto my-20">
        <div class="head-titles text-center">
            <h1 class="font-extrabold text-9xl px-5">Activity</h1>
        </div>
        <div class="customize-hr flex justify-center mb-8">
            <div class="hr my-5"></div>
        </div>
        <div class="grid grid-cols-3 xl:grid-cols-3 lg:grid-cols-2 gap-5 md:px-5 lg:px-5 xl:px-0">

            <a href="{{route('view-detail-01')}}" class="card col-span-3 sm:col-span-3 lg:col-span-1">
                <div class="overflow-hidden shadow-lg border w-[100%]">
                    <div class="card-img">
                        <div class="card-img-hvr">
                            <img class="w-full" src="{{asset('assets/img/Card/img-activity-01.png')}}" alt="Sunset in the mountains">
                        </div>
                    </div>
                    <div class="px-6 py-4">
                        <div class="title-card font-bold text-xl mb-2 line-clamp-2">To inspire your team to band together and celebrate collaboration, we've gathered some of our favorite quotes on the power of teamwork.</div>
                        <p class="card-para text-gray-600 text-base line-clamp-3">
                            Because it's true: Teamwork has the incredible power to increase productivity, job satisfaction, and even each person's individual performance.
                            To inspire your team to band together and celebrate collaboration, we've gathered some of our favorite quotes on the power of teamwork. Check out the full list of inspirational quotes below, including some remarks about hard work to keep your collaborative juices flowing.

                            Alone we can do so little; together we can do so much." - Helen Keller
                            Talent wins games, but teamwork and intelligence win championships." - Michael Jordan
                            Teamwork begins by building trust. And the only way to do that is to overcome our need for invulnerability." - Patrick Lencioni
                            It is literally true that you can succeed best and quickest by helping others to succeed." - Napolean Hill
                            If you want to lift yourself up, lift up someone else." - Booker T. Washington
                            None of us, including me, ever do great things. But we can all do small things, with great love, and together we can do something wonderful." - Mother Teresa

                        </p>
                    </div>
                </div>
            </a>
            <a href="{{route('view-detail-02')}}" class="card col-span-3 sm:col-span-3 lg:col-span-1">
                <div class="overflow-hidden shadow-lg border w-[100%]">
                    <div class="card-img">
                        <div class="card-img-hvr">
                            <img class="w-full" src="{{asset('assets/img/Card/card-img-03.jpg')}}" alt="Sunset in the mountains">
                        </div>
                    </div>
                    <div class="px-6 py-4">
                        <div class="title-card font-bold text-xl mb-2 line-clamp-2">Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing</div>
                        <p class="card-para text-gray-600 text-base line-clamp-3">
                            The CCC is comprised of representatives of stakeholder constituencies represented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS,
                            TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.

                            TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.
                            TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.
                        </p>
                    </div>
                </div>
            </a>
            <a href="{{route('view-detail-01')}}" class="card col-span-3 sm:col-span-3 lg:col-span-1">
                <div class="overflow-hidden shadow-lg border w-[100%]">
                    <div class="card-img">
                        <div class="card-img-hvr">
                            <img class="w-full" src="{{asset('assets/img/Card/card-img-02.jpg')}}" alt="Sunset in the mountains">
                        </div>
                    </div>
                    <div class="px-6 py-4">
                        <div class="title-card font-bold text-xl mb-2 line-clamp-2">The importance of teamwork for agility at work</div>
                        <p class="card-para text-gray-600 text-base line-clamp-3">
                            You've likely heard the saying, “The whole is greater than the sum of its parts.” And while Aristotle was not referring to teamwork, the statement expresses the main goal of building a great team.
                            A team can achieve far more than any individual working alone. That's obvious. But through teamwork, a team should be able to achieve far more than all of the individual members working alone.
                            Most of us have been on teams where we wouldn't say that is always the case.
                            It takes more than one brilliant mind to achieve a goal, especially as the issues we're trying to solve become more complex, no single person has all of the information, context, and skills needed. It takes a team for great ideas to come to life.
                            Why is being part of a team not always fulfilling?
                            You can’t simply put a group of people into a room and expect miracles to happen. Utilizing the diverse talents and perspectives of team members, having a clear shared objective, and effective collaboration all help give a team the power to grow and succeed.
                            Done right, working together and being part of a team drives success for the individual and the company. When a team grows and learns, so does the company's ability to be agile and create value for customers.
                            Each team member's skills and abilities should grow faster as well.
                            That's the power of great teamwork.
                            Let’s take a look at the importance of teams and how to make teamwork work in the workplace.
                        </p>
                    </div>
                </div>
            </a>
            <a href="{{route('view-detail-02')}}" class="card col-span-3 sm:col-span-3 lg:col-span-1">
                <div class="overflow-hidden shadow-lg border w-[100%]">
                    <div class="card-img">
                        <div class="card-img-hvr">
                            <img class="w-full" src="{{asset('assets/img/Card/img-activity-04.webp')}}" alt="Sunset in the mountains">
                        </div>
                    </div>
                    <div class="px-6 py-4">
                        <div class="title-card font-bold text-xl mb-2 line-clamp-2">The CCC shall normally hold four regular meetings per calendar year at approximately quarterly intervals. A calendar of regular meetings shall be prepared by the CCC</div>
                        <p class="card-para text-gray-600 text-base line-clamp-3">
                            The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituencies represented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance the performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituencies represented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, Test
                            TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund. The purpose of the CCC is to enhance the performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituencies represented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.
                        </p>
                    </div>
                </div>
            </a>
            <a href="{{route('view-detail-01')}}" class="card col-span-3 sm:col-span-3 lg:col-span-1">
                <div class="overflow-hidden shadow-lg border w-[100%]">
                    <div class="card-img">
                        <div class="card-img-hvr">
                            <img class="w-full" src="{{asset('assets/img/Card/img-activity-05.jpg')}}" alt="Sunset in the mountains">
                        </div>
                    </div>
                    <div class="px-6 py-4">
                        <div class="title-card font-bold text-xl mb-2 line-clamp-2">The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.</div>
                        <p class="card-para text-gray-600 text-base line-clamp-3">
                            The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS,
                            TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.


                            TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.
                            TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.
                        </p>
                    </div>
                </div>
            </a>
            <a href="{{route('view-detail-02')}}" class="card col-span-3 sm:col-span-3 lg:col-span-1">
                <div class="overflow-hidden shadow-lg border w-[100%]">
                    <div class="card-img">
                        <div class="card-img-hvr">
                            <img class="w-full" src="{{asset('assets/img/Card/card-img-06.jpg')}}" alt="Sunset in the mountains">
                        </div>
                    </div>
                    <div class="px-6 py-4">
                        <div class="title-card font-bold text-xl mb-2 line-clamp-2">The CCC shall normally hold four regular meetings per calendar year at approximately quarterly intervals. A calendar of regular meetings shall be prepared by the CCC.</div>
                        <p class="card-para text-gray-600 text-base line-clamp-3">
                            The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS,
                            TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies. The CCC is a multi-sectoral national platform to coordinate and facilitate Global Fund activities to fight against HIV/AIDS, TB and malaria in Cambodia.The CCC is comprised of representatives of stakeholder constituenciesrepresented at the national level. The mandate of the CCC is to mobilize a national multi-sectoral response to develop and submit proposals to the Global Fund to scale up the fight against HIV/AIDS, TB and malaria, and to oversee and support the implementation of activities that are initiated by the CCC in line with national program priorities and supported by the Global Fund.The purpose of the CCC is to enhance performance of the Global Fund activities in Cambodia in partnership with stakeholder constituencies, to promote efficient program implementation, to avoid duplication by harmonizing Global Fund activities with other programs throughout Cambodia, and to strengthen coordination among stakeholder constituencies.
                        </p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</section>